--still set up simple stuff...
return {
  --"ellisonleao/gruvbox.nvim",
  --'nvim-lualine/lualine.nvim',
  --'nvim-treesitter/nvim-treesitter',
  --"nvim-lua/plenary.nvim",
  --'nvim-tree/nvim-web-devicons',
  --'nvim-tree/nvim-tree.lua',
  --{--LSP config & plugins
    --"neovim/nvim-lspconfig",
    --dependencies = {
      --automate install LSPs
      --"williamboman/mason.nvim",
      --"williamboman/mason-lspconfig.nvim",
      --useful satus update for LSP
      --'j-hui/fidget.nvim',
      -- additional lua config
      --'folk/neodev.nvim',
    --},
  --},
}